Solved tasks from 1-module"
js-tasks-ru/jsbasic-20230428_vladimir-mihaylov pull request #2
Opened 2023-05-02 14:44 UTC by Mikhailov-Vladimir

Решил задачи 1-5 из модуля первого.

2023-05-02 14:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-02 15:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-03 13:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-03 13:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-03 13:49 UTC, SinimaWath requested changes

2023-05-03 13:49 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Достаточно сложная реализация, давай пытаться упрощать.
- Используй метод `includes(' ')` - чтобы проверить на вхождение строки
- Условия можно уместить в одну строку: `return Boolean(name) && .... && ... `

2023-05-03 13:49 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return result;
Давай тут используем метод: `slice()` -> `str.slice(1)`

2023-05-03 13:49 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
`return result.indexOf(signature1) !== -1 || result.indexOf(signature2) !== -1`, if тут не нужен, так как операция возвращает boolean

2023-05-03 13:49 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return res + "…";
Давай тут тоже используем метод slice

2023-05-16 13:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-17 06:54 UTC, SinimaWath approved these changes

2023-05-17 06:55 UTC, merged